clusterZone: "mordasiewicz.local"
controller:
  jenkinsAdminEmail: r.mordasiewicz@f5.com
  image: "robinhoodis/jenkins"
  tag: "2.332.1-39"
  tagLabel: 2.332.1-39
  disableRememberMe: true
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  jenkinsUrl: http://jenkins.f5.mordasiewicz.com:8080
  installPlugins: []
  installLatestSpecifiedPlugins: true
  JCasC:
    defaultConfig: true
    configScripts:
      custom-configs: |
        unclassified:
          gitSCM:
            globalConfigEmail: "robin@mordasiewicz.com"
            globalConfigName: "robinmordasiewicz"
        jenkins:
          systemMessage: "Pipeline Jobs"
        jobs:
          - script: >
              pipelineJob('create-jenkins-container') {
                properties {
                  githubProjectUrl('https://github.com/robinmordasiewicz/jenkins-pipeline')
                  pipelineTriggers {
                      triggers {
                        githubPush()
                      }
                   }
                }
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/robinmordasiewicz/jenkins-pipeline.git')
                        }
                        branch('main')
                        extensions {}
                      }
                    }
                  }
                }
              }
          - script: >
              pipelineJob('create-nginx-container') {
                properties {
                  githubProjectUrl('https://github.com/robinmordasiewicz/nginx-pipeline')
                  pipelineTriggers {
                      triggers {
                        githubPush()
                      }
                   }
                }
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/robinmordasiewicz/nginx-pipeline.git')
                        }
                        branch('main')
                        extensions {}
                      }
                    }
                  }
                }
              }
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "${chart-admin-username}"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
agent:
  jenkinsUrl: http://jenkins:8080
  jenkinsTunnel: jenkins-agent:50000
  resources:
    requests:
      cpu: "2048m"
      memory: "2048Mi"
    limits:
      cpu: "2048m"
      memory: "2048Mi"
  podName: "jenkins-agent"
persistence:
  size: "20Gi"
rbac:
  create: true
checkDeprecation: true
